Deploys to https://themangrove.vercel.app/. Instead of clicking on the text-box and thereby triggering the handleSignIn(e) method, we want to place the cookie on the user’s browser if the user has successfully signed in.
Before that, want to fix the Heroku deployment. That is for the current Heroku deployment that is on adf8d5079a095fa1c995506024d3d12f36994c5f, and which returns an Internal Server Error because it Cannot find module ‘react-cookie’.

We want to be able to push to the Heroku repository. The Build failed because of webpack errors: Module not found: Can’t resolve ‘./LoginCookies.js’ in ‘/tmp/build_3624d3a4/pages’. This implies that LoginCookies is imported before ProfilePage because otherwise we would have gotten this error not just for LoginCookies but also for ProfilePage.

Then, having deleted the “new” loginCookies and profilePage components, leaving us with the the Error: Cannot find module ‘react-cookie’.

After running `heroku run bash` to log into a Heroku instance, you can run `node` to enter a REPL, and require the paths directly (javascript - Heroku + Node: Cannot find module error - Stack Overflow
https://stackoverflow.com/questions/19341975/heroku-node-cannot-find-module-error), that is try setting `heroku config:set NODE_MODULES_CACHE=false`. Then, you might use `git mv` to rename the file locally then reupload it to fix the requiring file which does not exist issue.

Have the Node Modules been installed? (node.js - How to check whether Nodejs node modules are installed or not in Heroku - Stack Overflow
https://stackoverflow.com/questions/41044246/how-to-check-whether-nodejs-node-modules-are-installed-or-not-in-heroku).
~ $ npm list
example-app@1.0.0 /app
+-- express@4.18.1
+-- next@12.2.5
+-- react-dom@17.0.2
+-- react-snowfall@1.2.1
+-- react@17.0.2
`-- sweetalert@2.1.2
.

heroku config:set USE_NPM_INSTALL=true
node.js - Heroku not installing dependencies when deploying app - Stack Overflow
https://stackoverflow.com/questions/25458238/heroku-not-installing-dependencies-when-deploying-app.

On Heroku,
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        USE_NPM_INSTALL=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=false.

Connecting to Heroku Postgres | Heroku Dev Center
https://devcenter.heroku.com/articles/connecting-heroku-postgres

Makes a fork (gladishd/Da-Repo: For Vercel: Create a New Project!
https://github.com/gladishd/Da-Repo) of the da-repo repository (thellllvirtuoso/Da-Repo
https://github.com/thellllvirtuoso/Da-Repo) to create a new project: themangrove.vercel.app.
Project Settings – Dashboard – Vercel
https://vercel.com/gladishd/mangrove/settings/domains
Deploy a node server to Vercel | Full-ish Stack Developer
https://blog.devsharma.live/deploy-a-node-server-to-vercel

How does Vercel get permission to pre-populate the URL field with a “URL” da-repo-umyb.vercel.app while we can’t change it to something similar without putting the full URL? The URL recognition of Git is stronger for us than it is for Vercel. Therefore, we are setting it to the full URL https://themangrove.vercel.app/, which results in themangrove.vercel.app/ being a thing.

This is our account username: q92jwae@email.com password: password. :)

git remote add fork-origin https://github.com/gladishd/Da-Repo.git