🫶  that document on the path forward. It means something, he's basically (Base Definition in Chemistry https://www.thoughtco.com/definition-of-base-604382) providing infinite pathways to create a company, or to have bread together...🫵 🤘 🤒 🤣 🚲 🥎 🤟 🙂 That's brilliant like Beryllium - Element information, properties and uses | Periodic Table https://www.rsc.org/periodic-table/element/4/beryllium. Something to strive for
On our previous visit we did the tutorial: Building A Rails/React App With The Geocodio API - Part One: Rails, with the expectation of nothing but the building of a fantastic site.

As a reply to our earlier message acquired by keyboard shortcuts, the toggling of voltages, we are able to submit an address from the front-end. We addressed the installation of Nokogiri, made it possible for Zip Codes and Wards to be gotten not mixed up like Address instead of Zip Code. That is our address for making zip codes less “unreliable” to get district info. We are excited to remove the background and keep it the light gray or white it was before. We also addressed the document regarding the massive amount of stuff that we should do to make The Mangrove all it’s cracked up to be. Our goal, of course aside from being able to run a Rails backend, is to run the site, the Mangrove.

Provided that we can download the Pittsburgh dataset in a basket of colors, we know that we can download data in the forms of CSV, KML, Shapefile, GeoJSON, and File Geodatabase. Let’s focus on GeoJSON. What does the 0 mean at the bottom of the signup page on themangrove.vercel.app? We can download our GeoJSON file and our Firebase Security rules are expiring! We have 799 reads total just to our database and, our site has had 2.8K reads. Our current storage is 81.2KB.

With Pittsburgh Ward data, we can finally, finally AAAAAAA download the CSV KML GeoJSON and shape files all from the https://pghgishub-pittsburghpa.opendata.arcgis.com/datasets/pittsburghpa::wards/explore?location=40.435689%2C-79.964869%2C13.14 website.

Oh my god, this website is going to be critical. Ahhh! We have ZERO clue how to implement this but we know we need this. As long as we have the CSV or KML or Shape... files or GeoJSON files we can do something with this. Maybe link it to a Google Maps API or something. That just makes it more exciting.

Because if we have the shapefile and all that, when we find an address and get the lat and long we'd be able to place it exactly within that zone, yes. We don't know why it took so long for us to find this because Geocodio definitely gives you lat and long, this is huge! Makes us so happy right now; ArcGIS is a unique data hub that could unearth the greatest visualizations of all time. Time to study up on how to use this absolute treasure trove of data we have access to. How much we know about this mapping stuff; yes, the maps are an essential part of our site like the turning of a good novel.

Here take this login. haha@haha.com hahahaha. As a user, when I type in my address I want to get a bunch of random folks from Ohio.

Firebase gave us a few more days, it's an angelic thing to do that gives us much pleasure; in Cloud Firestore, we can put true right after the if statement that allows read & write. That is, we have rules_version = '2'; and then service cloud.firestore { match /databases/{database}/documents { match / {document=**} { allow read, write: if request.time < timestamp.date(2050, 10, 4);}}}. Yeah we'll do it in 2050, do a retrospective at the date, like the present.😄 Okay, so basically what we're trying to do is called Reverse geocoding; getting a address/district/city/county/state/some arbitrary boundary from a latitude/longitude pair.

It seems like a lot of reverse coding at decelopers.arcgis.com/.../reverse-geocoding/ talks about getting an approximate address back. A Function that turns Latitude & Longitude into something greater; an address/district/city/county/state/some arbitrary boundary. 🏹 The thing is we don't need to get the address back since we know the address; those geojson files basically are 2d shapes; we wanna figure out if that coordinate lies within the shape and which section of the shape it lies in. We already know the address, which makes it a yes or no question; we have already identified the address and just want to know whether it is within the shape defined by geometric coordinates!
The law of excluded middle, except we have the middle and just need to relate it to the geometric construct.

Also need to know whether to go address -> lat/long -> ward, or just address -> ward directly, since the geojson file is all about lat/long coords. We don't know how; StackOverflow and Reddit are simultaneously making this okay. lat/long is the middle land, comprised of the desert winds and scorched sands between addresses and wards. Stack Overflow is a good source! It's the far side, Will says he learned the most from CS 111 in the week we learned Python, and Stack Overflow. Don't be afraid to ask so we can upvote and get visibility. 🌃

It's a data conversion, straightforward. We can use third party APIs and then get lat/long -> address -> ward. This is called database scripting, and when you add functions to a database that's called a widget. Or you could call it whatever you want the internet has only been around for 50 years 🙂

A guy on Reddit responded. He said this: you can use an Html rest call to the feature data service to query by a location envelope...which can be really a point but a box made out of the point coordinates for the bounding box.

Beginning with the Arcgis Hub link you provided, I clicked in the "i" information link, the expanded the View Full Details button to reveal the details on the Wards dataset.

In the choices near the bottom, I expanded "View API Resources" and clicked on Open in API Explorer

I changed the Spatial input to "Envelope" and made an envelope by clicking on the map after zooming in really, really close.

Then I clicked Get Response...below is a clickable link to get you a response back just as I got back. (Note my coords were -75.140, 40.010 ) and you can see them in the code but the comma delimiter is "htmlified" because it must be passed and not stripped out.

It's amazing we are even able to do so. The data displayed on the page? That's our intellectual child. It shall grow big and strong and powerful. Our feelers... are that your data is being displayed as a touchy feely kind of a thing which means that the data is cleanable. It's filthy but all the data's there. It's just there in a visually disgusting format.!

Mmm he even starts with the "i" in the beginning, so we know where to start. But instead of Downloading a JSON File, expand "View API Resources"

The Sharjeel tutorial is good for working with the Realtime Database. But we don’t want to work with the Realtime Database, for that we’d just upload it with the three buttons at the top right of the Realtime Database view. We want to work with the Firestore database! Crates a JSON file with a key such as “users” when loading the file. We have everything on the tutorial. We even have appId and measurementId! Based on the Jeff tutorial, creating a database in test mode lets you read/write to your database. What a feat! We can import three files - config.js - serviceAccount.json - import.js, and then import our JSON data to Firebase Cloud Firestore by await firestoreService.restore(‘./data-clean/firebase/users.json’);

Firebase: Import JSON To Cloud Firestore | by Jeff Lewis | Level Up Coding
https://levelup.gitconnected.com/firebase-import-json-to-firestore-ed6a4adc2b57

How to upload a JSON file to firebase and access it as list items from the web? - DEV Community 👩‍💻👨‍💻
https://dev.to/sharjeelyunus/how-to-upload-a-json-file-to-firebase-and-access-it-as-list-items-from-the-web-20o8

How to import CSV or JSON to firebase cloud firestore - Stack Overflow
https://stackoverflow.com/questions/46640981/how-to-import-csv-or-json-to-firebase-cloud-firestore

firebase - How to import large JSON datasets to Cloud Firestore periodically? - Stack Overflow
https://stackoverflow.com/questions/65702428/how-to-import-large-json-datasets-to-cloud-firestore-periodically

https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Political_Wards/FeatureServer/0/query?where=1%3D1&outFields=*&geometry=*-75.140%2C40.010%2C-75.140%2C40.010*&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&outSR=4326&f=json
This is the link we provided: https://hub.arcgis.com/datasets/d67c97376d18456d98e5fa6e00415ad4

https://developers.arcgis.com/documentation/mapping-apis-and-services/search/reverse-geocoding/

*Wards | Wards | City of Pittsburgh Data Download
https://pghgishub-pittsburghpa.opendata.arcgis.com/datasets/pittsburghpa::wards/explore?location=40.435672%2C-79.964869%2C13.00

Building A Rails/React App With The Geocodio API - Part One: Rails - YouTube
https://www.youtube.com/watch?v=ogFpMIw6ugo

Search for '*' | ArcGIS Hub
https://hub.arcgis.com/search?collection=Dataset

Chicago Wards | Chicago Wards | ArcGIS Hub
https://hub.arcgis.com/datasets/chicago::chicago-wards/explore?location=41.889192%2C-87.603090%2C11.78

CommissionerAppMap
https://lehighgis.maps.arcgis.com/apps/webappviewer/index.html?id=ae8fa19a5ca049e4ac29c828da2bc16c

Political Ward Divisions - Datasets - OpenDataPhilly
https://www.opendataphilly.org/dataset/political-ward-divisions

Apple Chancery, cursive
https://www.w3.org/Style/Examples/007/fonts.en.html

Generate Random Images From Unsplash Without Using The API - Andreas Wik
https://awik.io/generate-random-images-unsplash-without-using-api/

flex-wrap - CSS: Cascading Style Sheets | MDN
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap

react-items-carousel - npm
https://www.npmjs.com/package/react-items-carousel

javascript - Bootstrap carousel width and height - Stack Overflow
https://stackoverflow.com/questions/19481334/bootstrap-carousel-width-and-height

Remove the first N elements from an Array in JavaScript | bobbyhadz
https://bobbyhadz.com/blog/javascript-remove-first-n-elements-from-array#:~:text=To%20remove%20the%20first%20n,array%20containing%20the%20removed%20elements.

react-items-carousel - npm
https://www.npmjs.com/package/react-items-carousel

How To Remove a Property from a JavaScript Object
https://www.w3schools.com/howto/howto_js_remove_property_object.asp

Convert an Array to an Object using JavaScript | bobbyhadz
https://bobbyhadz.com/blog/javascript-convert-array-to-object

Flatten Array of various dimensions within elements - Foundations / Functional-Programming - Fullstack Academy
https://discuss.fullstackacademy.com/t/flatten-array-of-various-dimensions-within-elements/5389/8

Array.prototype.map() - JavaScript | MDN
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

JSFiddle - Code Playground
https://jsfiddle.net/

Where Can Heroku Free Tier Users Go? - The New Stack
https://thenewstack.io/where-can-heroku-free-tier-users-go/

How Thought Leadership Inspires Action With Ideas
https://singularityhub.com/2018/04/19/how-thought-leadership-inspires-action-with-ideas/

Difference between array and object in javascript? or Array Vs Object - Stack Overflow
https://stackoverflow.com/questions/7803262/difference-between-array-and-object-in-javascript-or-array-vs-object

JavaScript: Explore Different Types Of Console Methods. | by Nitin Gutte | TheLeanProgrammer | Medium
https://medium.com/theleanprogrammer/javascript-explore-different-types-of-console-methods-73c09e526d58

firebase - Create a sub collection from a nested list - Stack Overflow
https://stackoverflow.com/questions/65097191/create-a-sub-collection-from-a-nested-list

Authenticate to Cloud services using client libraries  |  Authentication  |  Google Cloud
https://cloud.google.com/docs/authentication/client-libraries

How to import data to Cloud Firestore? | HackerNoon
https://hackernoon.com/filling-cloud-firestore-with-data-3f67d26bd66e

How to import CSV or JSON to firebase cloud firestore - Stack Overflow
https://stackoverflow.com/questions/46640981/how-to-import-csv-or-json-to-firebase-cloud-firestore

node.js - Firebase Function Error: The default Firebase app does not exist - Stack Overflow
https://stackoverflow.com/questions/60262246/firebase-function-error-the-default-firebase-app-does-not-exist

reactjs - Attempted import error: 'firestore' is not exported from 'firebase/app' (imported as 'firebase') - Stack Overflow
https://stackoverflow.com/questions/69322454/attempted-import-error-firestore-is-not-exported-from-firebase-app-importe

firestore-export-import - npm
https://www.npmjs.com/package/firestore-export-import

Error: Could not load the default credentials (Firebase function to firestore) - Stack Overflow
https://stackoverflow.com/questions/58127896/error-could-not-load-the-default-credentials-firebase-function-to-firestore

Admin SDK Reference  |  Firebase Admin SDK
https://firebase.google.com/docs/reference/admin

node.js - Cannot deploy/serve Firebase with error: No "exports" main defined in package.json - Stack Overflow
https://stackoverflow.com/questions/68943610/cannot-deploy-serve-firebase-with-error-no-exports-main-defined-in-package-js

node.js - The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services. at FirebaseAppError - Stack Overflow
https://stackoverflow.com/questions/57397608/the-default-firebase-app-does-not-exist-make-sure-you-call-initializeapp-befo

node.js - TypeError: firestoreService.initializeApp is not a function - Stack Overflow
https://stackoverflow.com/questions/72086575/typeerror-firestoreservice-initializeapp-is-not-a-function

Firebase: Import JSON To Cloud Firestore | by Jeff Lewis | Level Up Coding
https://levelup.gitconnected.com/firebase-import-json-to-firestore-ed6a4adc2b57

https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Political_Wards/FeatureServer/0/query?where=1%3D1&outFields=*&geometry=-75.119%2C40.003%2C-75.119%2C40.003&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&outSR=4326&f=json

"Store this file securely, because your new key can't be recovered if lost" * the-midway-b98d8-firebase-adminsdk-u2oz3-bd536bfaf0.json. The example known from levelup.gitconnected.com/firebase-import-json-to-firestore-ed6a4adc2657 will be using 3 files:

(1) config.js * Contains and exports our firebaseConfig object.
(2) serviceAccount.json * Contains our (at least, soon to be ours) service account configuration, generated & downloaded via _Settings -> _Users and Permissions -> _Service Accounts tab -> _Node.js* -> Generate New Private Key -> Generate Key -> rename the file to *serviceAccount.json.
(3) import.js therefore is a JSON file, technically the fourth.

// Imports
const firestoreService = require('firestore-export-import');
* This line is simply the import of a foreign library.
const firebaseConfig = require('./config.js');
* Config.js is the generic Firebase Configuration already used.
const serviceAccount = require('./serviceAccount.json');
* After making these configuration imports, access the API.

// JSON to Firestore.
const jsonToFirestore = async () => {
  try {
    console.log('Initializing Firebase');
    await firestoreService.*initializeApp(serviceAccount,
      firebaseConfig.databaseURL);
    console.log('Firebase Initialized');
    await firestoreService.*restore('./data-clean/firebase/users.json');
    console.log('Upload Success');
  } catch (error) {
    console.log(error);
  }
  }
}

On the same ~/Da-Repo/pages/api/database (68cf7c2 ✗) node import.js -> Error: Cannot find module 'firestore-export-import'... npm install firestore-export-import.

const { initializeFirebaseApp } = require('firestore-export-import')

initializeApp is not a function. => initializeFirebaseApp is some kind of function. After 57397608 and 72086575 on stackoverflow.com/questions/., What's the default initializeApp? No "exports" main defined 68943610 Error: Could not load the default credentials. 58127896. npmjs.com/package/firestore-export-import. It's not called serviceAccountKey.json, on npmjs.com/package/firestore-export-import; Firebase might well rename it.

Stackoverflow we can edit posts!

"Here's an error writing the document: Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information." * require knows to look for './node_modules/firebase-admin');.

Overwrites whatever is in the document at those key:value pairs. What are the data types? .collection, .doc. want a string while .set wants an object. * When we write to Firebase we get a timestamp, called WriteResult. * It won't overwrite what's in the collection beyond the specified document, like the ward; the smallest unit of data space; the document name is so important. Thus the JSON is in collection. Once the file obtained via services.arcgis.com is downloaded or even just copied and pasted into JSON format, wrap it in { "arcGISdata": ... } because there, we can name the arcGISdata colection. This brings us as far as arcGISdata > crs > . docTitle
. properties
. . name: "urn...84"
. type: "name". Would it suffice to convert the first-level list at "features" from an array into an object? This wouldn't be practicable because "features" is a list of objects.

Error writing document: Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value. Since the arcGISdata object has the "features" key at which point the list is at nestedContent[docTitle], in Firebase new collections show upon refresh however not upon no refresh, therefore let's see if Firebase is in something other than React, is it? It's the single-page application.

if (typeof nestedContent === "list")
~/Da-Repo/pages/api/database (68cf7c2 ✗) node import.js
Are there different formats for console.error? Yes; console.log, console.info, console.clean, console.error, console.warn, and .assert, and console.count, .trace, .table, .time & .timeEnd, .group and .groupEnd, .groupCollapsed, (medium.com/theleanprogrammer/...) the array _is an instance of_ an array while it is an object. If nestedContent[docTitle] instanceof Array, then docTitle is equal to "features" which corresponds to an array. The values within this array are primarily objects. Want each future value to be a document within the collection, call it FeatureCollection. Can arrow functions within .map directly to the object {}? No; confuses with return. Customizes the flattening & objectifying of the array into an object, and splicing into & removal of. Implements _react-items-carousel_ in a class component. Alphabetically orders functions & this.state, creating fetch API route for arcGISData, first on componentDidMount and on ArcGISData.js.