Adds IllinoisCountyEO.json data. Replaces for example "Adams County" with "Adams", by setting ` County"` as the criterion to replace with `"`. const [postData, setPostData. is a "native" built-in function ! Why not test it by importing the whole function, * We already have created, don't have title, we do have message, from which imports tags, and we still have selectedFile. Creator may be from the Cookie object. pages/actions/posts.js. Here we are doing import * as api from '../api/index.js'; index.js is a place to build & export functions. index.js is in social/client/src/api/index.js, originally. * Instead of pages/api/index.js, we can access pages/actions/postsAPI.js. Moves it to there (moves pages/api/index.js to pages/actions/posts). We have imported users.js, posts.js, postsAPI.js and (unused) styles.js. We are making some kind of comparison between pages/users.js and social/client/src/components/Form/Form.js. The currentId is actually passed as a property to pages/users.js. Form.js is "being" imported from social/client/src/App.js. * Only using getPosts from './actions/posts'; and therefore, since we turned api.fetchPosts() into export const getPosts, we know how to effectively fetch new posts, deal with the existing posts. Module not found : Can't resolve './components/Posts/Posts'. * Moved : social/client/src/components/Form/Form.js in the original tutorial,... to pages/users.js Moved : social/client/src/actions/posts.js in the original tutorial... to pages/actions/posts.js. Moved : social/client/src/api/index.js from the tutorial that is memories-project to pages/actions/postsAPI.js Moved : We did import, to pages/src/styles.js. These are in a category of their own!
Remember the pages/api/users.js, that initializes the firebase APP. All it does is await db.collection. Don't touch. just focus on pages/users.js. We have moved the /actions folder to still, as before, meet the working directory... and finally we Move : social/client/src/components/Posts/Posts.js to "pages/components/Posts/Posts.js".
Whoops! Importing Posts in users.js leads to importing Post in Posts. Instead of doing the importing of a file structure let's create Post.js adjacent with Posts.js both; in pages/components/Posts folder; it's a directory! A post within a Post means ..
In the meanwhile, we can face-to-face social/client/package.json with package.json--Da-Repo.
ReferenceError: setPostData is not defined. xD
Sets the post data function setPostData object postData.
Now, when submitting a message, currentId is not defined. Inadvertently merging Form.js & App.js, the currentId.