Good news: Ballotpedia does sell their data and API. Bad news: it's all like 12k+. Nothing over 20k though. If we get sufficient funding that'll be no problem, since once we have the API it'll be permanent; then we can devote research and a team to develop our own API. Focus on a state: first want to render the loginCookies component on * index.js: import ProfilePage from './profilePage.js'. Second, after rendering want to pass down what's currently in the this.state resurrection of the username & password fields. Third, the profilePage.js constructor(props) -> this.state = {...props, implicit as seen on ProfilePage name="Dean" />. Fourth along the lines of above within ProfilePage render <LoginCookies cookie={this.state.props} />. Fifth can we reach the Profile Page component? Yes. We are able to render the LoginCookies component through ProfilePage on index.js. Is Stack Overflow always offline? No.
Credits
rename - Changing capitalization of filenames in Git - Stack Overflow
https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git
node.js - Keep getting "cannot find module" errors when pushing React/Node app to Heroku - Stack Overflow
https://stackoverflow.com/questions/57548740/keep-getting-cannot-find-module-errors-when-pushing-react-node-app-to-heroku
How do I fix a missing module in my package.json? - Heroku Help
https://help.heroku.com/QMZ3RR7L/how-do-i-fix-a-missing-module-in-my-package-json
What Are Mangroves: Learn About The Importance Of Mangrove Plants
https://www.gardeningknowhow.com/ornamental/trees/mangrove/mangrove-information.htm
react-cookie - npm
https://www.npmjs.com/package/react-cookie
javascript - TypeError: react__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function - Stack Overflow
https://stackoverflow.com/questions/61388663/typeerror-react-webpack-imported-module-0-default-is-not-a-function
Document correct ES6 module usage to avoid "SyntaxError: import not found: default" · Issue #423 · js-cookie/js-cookie
https://github.com/js-cookie/js-cookie/issues/423
TypeError: Cookies.set is not a function · Issue #427 · js-cookie/js-cookie
https://github.com/js-cookie/js-cookie/issues/427
useLayoutEffect and server rendering
https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85
How passing props to component works in React - LogRocket Blog
https://blog.logrocket.com/the-beginners-guide-to-mastering-react-props-3f6f01fd7099/
Ballotpedia API
https://developer.ballotpedia.org/