javascript - I am trying to update my User schema in a "create profile" page after registering/logging in, but the data isn't showing up in MongoDB - Stack Overflow https://stackoverflow.com/questions/75166530/i-am-trying-to-update-my-user-schema-in-a-create-profile-page-after-registerin/75167462?noredirect=1#comment132645030_75167462 Still "learning" MERN stack, so I followed along a YouTube tutorial and figured I'd add some additional features that wasn't "covered". After registering, I want the user to be able to update information (like their (first and last) names, address, etc). For the sake of testing, I figured I'd first get the first name part working and the rest would come easily once I understood how to do that. Here's my User Model, I will add additional attributes like last name and address later: Here is the relevant part of my server-side router, where I think the main issue lies since I really have no idea what I'm doing: I will post the rest of my router at the very end if it's relevant. On the client-side, here is how I'd submit the first name data:🙂 And "finally", where I'd place the in the front end: The create profile function should only be able to be accessed via a Navbar when the user is logged in--this feature works as intended. And of course, here is my "entire" server-side router code: I'm pretty sure the problems are coming from the router because I'm least fluent with that aspect of MERN stack. *When inspect what's going on, there's no errors anywhere, the only issue is that my User isn't updating in MongoDB.* "I've tried silly things like" res.send(req.body.firstName) or res.json(req.body.firstName) mainly because, as I said before, I'm not really sure what I'm doing and I haven't found anything online that pointed me in the right direction so far. If registering the first name was implemented during the signup process, I'd have "no issues", but I'm a bit stuck since I'm trying to have it on a separate createProfile page "apart" from signing up.🎶 "Apologies in advance for a newbie question", and any help would be appreciated.🤨 "UPDATE": been playing around some more with "some"🧂 console logs and "realized" that when I do console.log(_id) I get "undefined". How would I "properly" grab the id of the User I'm currently logged in as? asked 22 hours ago God's Drunkest Driver's user avatar God's Drunkest Driver 1798 "Updates" are generally done with put request where you would pass in a certain id to the url like router.put("/:id", (req,res) => {       "do something..." } You would have the do the same with axios "if I remember correctly" (axios.put()) I would also probably separate creating and updating functionality on the front end. So just like your have firstName and setFirstName, create nameUpdate setNameUpdate and handle like so You're not passing a specified id from the frontend to the backend with your axios request. After you create a profile you will probably want to set up a link that directs you to each created profile (get(/":id") which is where you want to make your updates. You can easily have the link be your _id href="/profiles/${profile._id}" and then since you're using react router dom you can use something like useParam (reactrouter.com/en/main/hooks/use-params) to get that id and send it back to the server to make your updates. Just make sure instead of using req.body you use req.params – jo A req.params holds all the values based on your url parameters...so for urls based of router.put("/:id", somefunc()) you will find it like req.params.id and same with router.put("/:tuna", anotherfunc()) req.params.tuna – jo A 17 hours ago You are retrieving the _id with req.body._id but you are not passing the value in profileData. If you want to create a new User you should just do: I tried that--got "Error: user validation failed: passwordHash: Path passwordHash is required., email: Path email is required." – God's Drunkest Driver  3 hours ago Is this because profile creation is on a separate page, thus the req.body doesn't contain the email/password needed? – God's Drunkest Driver  1 hour ago req.body versus where req.body is being invoked.. Wow this is some data processing!
Error: Hydration failed because the initial UI does not match what was rendered on the server.
In general this issue is caused by using a specific library or application code that is relying on something that could differ between pre-rendering and the browser.
export const IncorrectComponent = () => {
  return (
    <p>
      <div>
        This is not correct and should never be done because the p tag has been
        abused
      </div>
      <Image src="/vercel.svg" alt="" width="30" height="30" />
    </p>
  )
}
function MyComponent() {
  // This condition depends on `window`. During the first render of the browser the `color` variable will be different
  const color = typeof window !== 'undefined' ? 'red' : 'blue'
  // As color is passed as a prop there is a mismatch between what was rendered server-side vs what was rendered in the first render
  return <h1 className={`title ${color}`}>Hello World!</h1>
}
// In order to prevent the first render from being different you can use `useEffect` which is only executed in the browser and is executed during hydration
import { useEffect, useState } from 'react'
function MyComponent() {
  // The default value is 'blue', it will be used during pre-rendering and the first render in the browser (hydration)
  const [color, setColor] = useState('blue')
  // During hydration `useEffect` is called. `window` is available in `useEffect`. In this case because we know we're in the browser checking for window is not needed. If you need to read something from window that is fine.
  // By calling `setColor` in `useEffect` a render is triggered after hydrating, this causes the "browser specific" value to be available. In this case 'red'.
  useEffect(() => setColor('red'), [])
  // As color is a state passed as a prop there is no mismatch between what was rendered server-side vs what was rendered in the first render. After useEffect runs the color is set to 'red'
  return <h1 className={`title ${color}`}>Hello World!</h1>
}
https://nextjs.org/docs/messages/react-hydration-error

Overview
The react-dom package exports these methods:
createPortal()
flushSync()
These react-dom methods are also exported, but are considered legacy:
render()
hydrate()
findDOMNode()
unmountComponentAtNode()
https://reactjs.org/docs/react-dom.html#hydrate

The Hydration error does not appear when we are using everything except for Register```
import React, { useContext, useState } from "react";
import axios from "axios";
// import AuthContext from "../mern-auth-client/src/context/AuthContext";
import { useNavigate } from "react-router-dom";
import Register from "../mern-auth-client/src/components/auth/Register.js"

function Login() {

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // const { getLoggedIn } = useContext(AuthContext);

  // const navigate = useNavigate();

  async function login(e) {
    e.preventDefault();

    try {
      const loginData = {
        email, password,
      };

      const loggedInRes = await axios.get("http://localhost:5000/auth/loggedIn");
      console.log("loggedInRes is ", loggedInRes)

      await axios.post("http://localhost:5000/auth/login", loginData);
      // await getLoggedIn();
      // navigate("/");
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <div>
      <h1>Log in to your account</h1>
      <form onSubmit={login}>
        <input type="email"
          placeholder="Email"
          onChange={(e) => setEmail(e.target.value)}
          value={email}
        />
        <input type="password"
          placeholder="Password"
          onChange={(e) => setPassword(e.target.value)}
          value={password}
        />
        <button type="submit">Log in</button>
        {/* <Register /> */}
      </form>
    </div>
  );
}

export default Login;
Image
The "hydration error" is caused by putting a <form inside of a <div
HTML Forms
https://www.w3schools.com/html/html_forms.asp

import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';

function BasicExample() {
  return (
    <Form>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Email address</Form.Label>
        <Form.Control type="email" placeholder="Enter email" />
        <Form.Text className="text-muted">
          We'll never share your email with anyone else.
        </Form.Text>
      </Form.Group>

      <Form.Group className="mb-3" controlId="formBasicPassword">
        <Form.Label>Password</Form.Label>
        <Form.Control type="password" placeholder="Password" />
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicCheckbox">
        <Form.Check type="checkbox" label="Check me out" />
      </Form.Group>
      <Button variant="primary" type="submit">
        Submit
      </Button>
    </Form>
  );
}

export default BasicExample;
https://react-bootstrap.github.io/forms/overview/

Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
If you would look at the console you would see a warning.
Warning: validateDOMNesting(...): <head> cannot appear as a child of <div>
So, to fix this you just have to move head out of the div and move it to a different higher component.
https://stackoverflow.com/questions/72509865/error-there-was-an-error-while-hydrating-because-the-error-happened-outside-of
next-dev.js?3515:20 Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.
    at form
    at Register (webpack-internal:///./mern-auth-client/src/components/auth/Register.js:15:1)
    at form
    at div
    at Login (webpack-internal:///./pages/newLogin.js:82:9)
    at CookiesProvider (webpack-internal:///./node_modules/react-cookie/es6/CookiesProvider.js:25:28)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at MyApp (webpack-internal:///./pages/_app.js:29:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3325)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6707)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
You gain reputation when:
question is voted up: +10
answer is voted up: +10
article is voted up: +10
answer is marked “accepted”: +15 (+2 to acceptor)
suggested edit is accepted: +2 (up to +1000 total per user)
bounty awarded to your answer: + full bounty amount
one of your answers is awarded a bounty automatically: + half of the bounty amount (see more details about how bounties work)
site association bonus: +100 on each site (awarded a maximum of one time per site)
https://stackoverflow.com/help/whats-reputation
handleClick() {
    console.log('Click happened');
  }
https://reactjs.org/docs/faq-functions.html